version: '3'
services:
  cartographer:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
     - '8080:8080'
     - '6060:6060'
    volumes:
      - '.:/opt/go/src/github.com/teastburn/cartographer'
    environment:
      - NR_KEY
    command: 'CompileDaemon -command="./cartographer -n=${NR_KEY} -s=${NR_SUFFIX}" -graceful-kill=true -log-prefix=false'
