version: '3'
services:
  cartographer:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
     - '8080:8080'
    volumes:
      - '.:/opt/go/src/github.com/teastburn/cartographer'
    command: 'CompileDaemon -command="./cartographer" -graceful-kill=true -log-prefix=false'



